### ISSUE TITLE
HTTP proxy

### ISSUE THREAD

**Issue by Ghiclgi** [slowphil/texmacs-win-builder#2]
I'm using windows 10. When I run the "setup-tm-sdk.bat", I got this message:
:: Synchronizing package databases...
error: failed to update mingw32 (unable to lock database)
error: failed to update mingw64 (unable to lock database)
error: failed to update msys (unable to lock database)
error: failed to synchronize any databases
error: failed to init transaction (unable to lock database)
error: could not lock database: Permission denied

There was a problem accessing the MSYS2 repositories
If your setup requires an HTTP proxy to access the web,
please specify it here, otherwise leave it empty.

HTTP proxy:

**Comment by slowphil** [comment]
Hi ghiclgi,
Thanks for the report. I've never seen such problem previously, and there is a slight chance it's only a temporary problem with the MSYS2 repos... 
However, even if the database problem you report did not exist, it's very likely that you would face other problems. Indeed I have serious reasons to suspect that it would not work because in the last ~ 2 months there have been changes in the TeXmacs repos regarding the build process, and I haven't taken the time to check if and how my script need to be adjusted to accommodate these changes. That's on my todo list and I'll comment again here when this is done.

**Comment by slowphil** [comment]
I have just check that the MSYS2 repos are working fine right now. And I confirm building TeXmacs is broken at the moment ( I need to make adjustments...).
Coming back to your issue: I note the "permission denied" : do you have write permission where you intend to install the sdk? Is this the first time you run the script?

**Comment by Ghiclgi** [comment]
Thanks for your comments. You're right. I ran the bat as administrator, then there is no proxy error.  However, I got
```
:: getopt and util-linux are in conflict
Could not install the remaining packages
```
As for TeXmacs, I'm using the svn10639M. I can't build the package either. Looking forward to your new release~

**Comment by slowphil** [comment]
slowphil/mingw-w64-texmacs was updated to accommodate for the changes in the svn repository (as of the present r10804, at least) and the build process should go through again now.
