### ISSUE TITLE
Error Installing the win-builder

### ISSUE THREAD

**Issue by msheakc** [slowphil/texmacs-win-builder#3]
I am trying to install the win-builder. Pacman seems to install mingw ok, but I get the following error message. 

error: target not found: mingw-w64-i686-qt4
error: target not found: mingw-w64-i686-poppler-qt4
==> ERROR: 'pacman' failed to install missing dependencies.

**Comment by slowphil** [comment]
Hi Michael,
Thanks again for reporting. The problem is that pacman no longer finds qt4 probably because of this [https://github.com/msys2/MINGW-packages/issues/3881](https://github.com/msys2/MINGW-packages/issues/3881). Nevertheless the binary still exists in the repo (for the moment).

I've commited a [fix](https://github.com/slowphil/texmacs-win-builder/commit/833ac4a1ed191fafc8dd6a29dd8b0af9a8bb470f) yesterday, by manually fetching qt4.

You should download the new `build-tm.sh` and run it in a MINGW32 terminal. If that's seems too technical, you can just clear the whole sdk directory and rerun the `texmacs-win-sdk-installer-0.93.7z.exe` (the installer always fetches the latest version of  `build-tm.sh`).

Best,
Philippe
