### ISSUE TITLE
Can't build on the latest TeXmacs

### ISSUE THREAD

**Issue by nerd-qp** [slowphil/texmacs-win-builder#7]
It appears that TeXmacs devs have either removed or moved the folder `src/TeXmacs/misc/inkscape_extension/`, erring the patching process.

**Comment by nerd-qp** [comment]
I manage to compile TeXmacs after commenting out this line: https://github.com/slowphil/mingw-w64-texmacs/blob/49c38f8e975d2ef0be33f609e18da9db50f210dc/PKGBUILD#L76 and tweaking the configure files myself -- it somehow creates a "bad" configure file with the wrong "WORD_MASK" in the config.h file. And of course, I need to use an older revision of the source code.

**Comment by slowphil** [comment]
Thanks for the heads up, Joy.

It was me who removed that outdated extension, and yes that broke my patches here. Like I said in the corresponding commit, my intention is to bring it back as a texmacs plugin in the trunk. The new code is finished, but it needs https://savannah.gnu.org/patch/?10177 to get accepted. Alas, that seems rather frozen for the moment, and the consequence is that the breakage did not resolve quickly in the way I was hoping. Sorry for that.

In the short term I guess I'll just update my patches here in Github with all my new code, but it is not ideal because extensive patching makes everything fragile and needing a lot of maintenance.
In any case I'll get around doing that in the next few days so that the latest code compiles.

**Comment by nerd-qp** [comment]
Thanks for the quick response, Phil!

I noticed the logs, yes. I see.

I also see the autoconf tool not working properly mentioned in there somewhere. But I have tried on the revisions after those commits and the configure script still cannot compile -- so the workaround I used was kind of necessary.

BTW, is it normal to not be able to use "ctrl+/" shortcut as "undo" in your modification (it is somehow bind to some functionalities related to _**TeXmacs comment**_ on my system: I removed my custom settings and set it to Emacs in preference after fresh installment)? I spent a couple hours trying to revert that behavior without progress. Maybe you could give some hints on this?

**Comment by nerd-qp** [comment]
Never mind on the last point, I found out that it was the kcomment module that's causing me troubles.

**Comment by slowphil** [comment]
Thanks for mentioning that too. I 'll change the komment plugin so that so it doesn't override any shortcut when not explicitly loaded.

**Comment by nerd-qp** [comment]
The updated script runs flawlessly. Thanks :) And it is built with Qt5, so it runs smoother!

**Comment by slowphil** [comment]
Glad it works for you now. I've also just uploaded a new sdk installer (the former one was no longer updating msys2 properly) and a new TeXmacs build too.
If issues show up in the Qt5 version, please do not hesitate to report them. None of the developpers use TeXmacs on windows; we need user feedback!
